name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
    validations:
      required: true
